name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy To AWS
      uses: aasmal97/deploy-react-app-to-aws
      with:
        aws_region: us-east-1
        aws_access_key_id: ${{ secrets.access_key_id }}
        aws_secret_access_key: ${{ secrets.secret_key }}
        cloudfront_distribution_id: ${{ secrets.distribution_id }}
        bucket_name: ${{ secrets.bucket_name }}
        react_app_secrets: ${{toJson(secrets)}}
        node_verison: 20
        path_to_app: ./dist